name: Deploy Go Backend to CentOS Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to CentOS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }} 
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            export GOPROXY=https://goproxy.cn,direct
            export CGO_ENABLED=1
            export GOOS=linux
            export GOARCH=amd64
            cd /root/gin-nextjs-blog/backend
            git pull origin main
            /usr/local/go/bin/go build -o blog-backend
            pkill blog-backend || true
            nohup ./blog-backend > backend.log 2>&1 &